# Generated by Django 6.0.2 on 2026-02-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_valoracion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='valoracion',
            name='unique_valoracionCursoEstudiante',
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='cursos.estudiante'),
        ),
        migrations.AddConstraint(
            model_name='valoracion',
            constraint=models.UniqueConstraint(fields=('curso', 'estudiante'), name='unique_valoracion_curso_estudiante'),
        ),
    ]
