# Generated by Django 6.0 on 2026-04-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='exercise',
            name='demo_gif_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exercise',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
