# Generated by Django 6.0 on 2026-04-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_body_part_exercise_demo_gif_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='demo_frame_paths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
