# Generated by Django 6.0 on 2026-05-05 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_fix_sin_material_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('workout_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.workoutplanitem')),
            ],
            options={
                'verbose_name': 'Sesion de ejercicio',
                'verbose_name_plural': 'Sesiones de ejercicio',
                'ordering': ('-session_date', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WorkoutExerciseSetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('reps', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('rir', models.CharField(blank=True, max_length=20)),
                ('notes', models.CharField(blank=True, max_length=160)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='workouts.workoutexercisesession')),
            ],
            options={
                'verbose_name': 'Serie realizada',
                'verbose_name_plural': 'Series realizadas',
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('session', 'order'), name='unique_session_set_order')],
            },
        ),
    ]
